### ISSUE TITLE
MVP functionality for plugin

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/gif2html5-plugin#1]
* [x] plugin hooks into attachment upload
* [x] if attachment=GIF, then post to middleware URL defined by filter.
* [x] middleware converts to mp4, mp4 is pushed to S3, and middleware sends the mp4 URL back to WP
* [x] WP stores the mp4 URL as attachment meta
* [x] WP filters post content to swap out the mp4 representation when it exists for the attachment
* [x] WP filters `get_attachment_image()` code to return mp4 representation when it exists for the attachment.

**Comment by mpatek** [comment]
@danielbachhuber OK to close this?
