### ISSUE TITLE
Update readme.txt to reflect implementation instructions

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/gif2html5-plugin#16]
We should make sure the setup steps are well-documented.

**Comment by mpatek** [comment]
@danielbachhuber how's the status of this right now? Should we add documentation about the new URL filters?

**Comment by danielbachhuber** [comment]
Can we have Installation instructions suggest filtering the option, instead of storing configuration in the database?

**Comment by danielbachhuber** [comment]
Looks pretty good now.
