### ISSUE TITLE
Using DOM API instead of regex to get node attributes

### ISSUE THREAD

**Issue by sboisvert** [fusioneng/gif2html5-plugin#20]
get_tag_attributes() would be more robust if it relied on the PHP DOM API instead of a regex since if height was entered as `<img height='100' />` instead of `<img height="100" />` (or any other also valid variation) it would fail. This is probably not a big deal since most of the images would be inserted via the UI and would follow the same pattern but could lead to strange bugs.

See also WP VIP Zendesk ticket 40312.

**Comment by danielbachhuber** [comment]
Fixed in #21. Thanks for the suggestion!

**Comment by sboisvert** [comment]
:+1:
