### ISSUE TITLE
Support filtering gif2html5 asset URL

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/gif2html5-plugin#28]
Because the middleware POSTs the S3 URL, we should support filtering the asset URL so we could use a Cloudfront URL instead.

**Comment by noppanit** [comment]
@mpatek I just want to make sure that I'm going in the right direction. 

I'm thinking of modifying this method https://github.com/fusioneng/gif2html5-plugin/blob/master/inc/class-gif2html5.php#L206 to be like 

```
	/**
	 * Get the mp4 URL for the given attachment.
	 *
	 * @param int $attachment_id The attachment ID.
	 * @return string The mp4 URL or, an empty string if no mp4 URL exists.
	 */
	public function get_mp4_url( $attachment_id ) {
		if ( apply_filters( 'cloudfront_url', '' ) ) {
			return  get_post_meta( $attachment_id, $this->mp4_url_meta_key, true ); // but replace https://s3.amazonaws.com/fusion-net-assets with whatever returns from add_filter('cloudfront_url')
		}
		return get_post_meta( $attachment_id, $this->mp4_url_meta_key, true );
	}
```

Do you think it's the right approach?

**Comment by noppanit** [comment]
Then this https://github.com/fusioneng/fusion-theme/blob/gif-plugin-dev/inc/integrations/class-gif2html5.php#L18 

can do some `add_filter`

**Comment by mpatek** [comment]
@noppanit that's pretty close to what I was thinking. How about like this:

```PHP
public function get_mp4_url( $attachment_id ) {
        return apply_filters( 'gif2html5_mp4_url', get_post_meta( $attachment_id, $this->mp4_url_meta_key, true ), $attachment_id );
}
```

Then in the gif2html5 integration (`inc/integrations/class-gif2html5.php` in the theme), we can add the filter to change the domain of the URL.

We should also do something analogous for `get_snapshot_url`.

**Comment by noppanit** [comment]
So the them will change the url instead of the plugin?

**Comment by mpatek** [comment]
@noppanit Right. The plugin will allow for filtering, and then the theme integration will actually make the change to the URL. We also might want to store domain in `functions.php` as a constant like `GIF2HTML5_URL_DOMAIN`.

**Comment by noppanit** [comment]
Can this one be closed?
