### ISSUE TITLE
Support Ogg Vorbis and WebM

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/gif2html5-plugin#36]
They're needed so the `<video>` tag works appropriately in all browsers.

See http://caniuse.com/#feat=video

Related https://github.com/fusioneng/gif2html5-app/issues/26

**Comment by noppanit** [comment]
Not sure if you started on this one? Do you need any help? @mpatek

**Comment by mpatek** [comment]
@noppanit I haven't started on this yet. I think it's fairly straightforward. I will work on this today.
