### ISSUE TITLE
Browsers download fallback img

### ISSUE THREAD

**Issue by mpatek** [fusioneng/gif2html5-plugin#37]
Even if browsers support the video formats, the fallback image is still downloaded.

Possible fixes:

* Use an `<object>` tag instead of an `<img>` tag as the fallback? 
* Use the same image URL for the video poster image and fallback image?

Some interesting discussion [here](http://www.smashingmagazine.com/2013/05/10/how-to-avoid-duplicate-downloads-in-responsive-images/)

**Comment by danielbachhuber** [comment]
> Use the same image URL for the video poster image and fallback image?

Wouldn't this be a GIF then?

**Comment by mpatek** [comment]
> Wouldn't this be a GIF then?

Yes, unless we want to use the snapshot PNG as both poster and fallback.

**Comment by mpatek** [comment]
Verified that the `<object>` method does work. Only the `.mp4` and `.png` poster image are downloaded.

**Comment by noppanit** [comment]
I just tried the fallback. It doesn't work for `video` tag

**Comment by noppanit** [comment]
I've found a solution which works on all browsers. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML5_audio_and_video#Error_handling 

It needs to be Javascript instead as Mozilla recommends. We would have to inject a bit of javascript to swap the gif with video that's broken.

**Comment by noppanit** [comment]
@mpatek  @danielbachhuber  should this be part of the plugin or the theme? I would think it would be part of the plugin?

**Comment by mpatek** [comment]
@noppanit I agree that it should be part of the plugin.

**Comment by danielbachhuber** [comment]
Leaving this issue open for a final round of testing when everything is on prod.

**Comment by noppanit** [comment]
@mkeppel @danielbachhuber good to close?
