### ISSUE TITLE
Large videos overflow the content

### ISSUE THREAD

**Issue by mpatek** [fusioneng/gif2html5-plugin#40]
Example GIF: https://fusiondotnet.files.wordpress.com/2015/05/sabradanielle-tumblr-com.gif

![image](https://cloud.githubusercontent.com/assets/1451430/7815052/1339a97c-0394-11e5-888b-0335a82cda6f.png)

This can be fixed by applying a `max-width: 100%` CSS rule on the `<video>` element. 

@danielbachhuber @noppanit should this be fixed as part of this plugin? Or should we put the fix in the Fusion theme?

**Comment by noppanit** [comment]
I think this should be part of the theme rather than the plugin as the plugin will be opensourced. But @danielbachhuber might have different opinion.

**Comment by danielbachhuber** [comment]
> I think this should be part of the theme rather than the plugin as the plugin will be opensourced.

:+1: 

Can we make sure to add some implementation note in `readme.txt`?
