### ISSUE TITLE
How to handle mobile?

### ISSUE THREAD

**Issue by noppanit** [fusioneng/gif2html5-plugin#43]
Chrome on Android is able to load `<video>` tag but `autoplay` is disabled by default. So, we have to use Javascript to play it manually. How do we want to deal with this?

**Comment by danielbachhuber** [comment]
We can just display the fallback image with some play button overlaid.

**Comment by noppanit** [comment]
On iOS, it displays play button by default. Will need to discuss with UX folks how should we handle this on how to put an indicator that this is a video. 

On Android, there's no play button by default.

I tested it. It works on Android and iOS. 

![screenshot 2015-05-27 22 17 54](https://cloud.githubusercontent.com/assets/638379/7851468/424fe89a-04be-11e5-8170-9f8152a257a2.png)

cc @FStop @lisaej

**Comment by danielbachhuber** [comment]
Buzzfeed has some play-ish icon like this:

![image](https://cloud.githubusercontent.com/assets/36432/7851870/8bda497e-04aa-11e5-9196-d13d1d254be8.png)

**Comment by mpatek** [comment]
Does it make sense to pause the video if the user touches it again?

**Comment by mpatek** [comment]
This plugin is looking great in all browsers I've tested so far, btw. Good job @noppanit

**Comment by noppanit** [comment]
@mpatek That's a good question. I'm going to ask UX folks.

**Comment by noppanit** [comment]
@mpatek On Buzzfeed. You cannot stop the video either. So, I think we can let it run. I'm going to close the issue now.
