### ISSUE TITLE
Use feature detection, not viewport width, to determine if video can autoplay

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/gif2html5-plugin#51]
See discussion in https://github.com/fusioneng/fusion-theme/pull/3016.

The plugin is currently inserting a play button when the viewport is less than 760 px wide. It would be better to do some kind of feature detection and only display the play button if the browser supports video element and one of the supported formats, but doesn't support the "autoplay" attribute on videos.

There is [a Modernizr test for video autoplay](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/video/autoplay.js), which could be useful as a reference or to build into the plugin.

**Comment by noppanit** [comment]
@goldenapples good to close?

**Comment by goldenapples** [comment]
Looks good to me.
