### ISSUE TITLE
Testing locally

### ISSUE THREAD

**Issue by noppanit** [fusioneng/gif2html5-plugin#60]
Just a question how do we test the conversion locally. Right now, I need to go on staging to test the plugin. Is there anyway I can test it locally? I try running the app inside vagrant but it doesn't work.

**Comment by mpatek** [comment]
I have been able to test by running the server inside Vagrant and setting the url to `localhost/convert`. That was a while ago, though, so it's possible that some change has prevented that. I will try re-testing sometime tomorrow.

**Comment by noppanit** [comment]
Closing as not relevant anymore.
