### ISSUE TITLE
Use fallback gifs for display on iOS devices

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/gif2html5-plugin#63]
The video experience on iOS devices is especially distracting to users, and our art department has expressed concern about fixing this. See (internal) [discussion here](https://fusionproduct.wordpress.com/2015/06/10/issues-with-gif2html5-video-behavior-on-ios/).

If the user's browser is detected as being an iOS device (using user agent string matching), the fallback gif should be loaded in place of the mp4 video. I guess we're going under the assumption that people using iPhones have money to burn and aren't concerned about bandwidth caps.

**Comment by danielbachhuber** [comment]
I'd prefer to make size a hard requirement too — we shouldn't ever serve GIFs over 1 MB.

**Comment by goldenapples** [comment]
> we shouldn't ever serve GIFs over 1 MB

That's reasonable in our case, but maybe a little too specific for a plugin? It'd be nice to expose some kind of filterable default behavior for themes to introduce their own logic like this.

**Comment by danielbachhuber** [comment]
> It'd be nice to expose some kind of filterable default behavior for themes to introduce their own logic like this.

Yep — filterable logic is what I was thinking.

**Comment by goldenapples** [comment]
Addressed in #78.
