### ISSUE TITLE
Integrating mp4-backed GIF images into a theme

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/gif2html5-plugin#8]
@mpatek [sez](https://github.com/fusioneng/gif2html5-plugin/pull/5#issuecomment-95621497):

> Unfortunately, I don't think the wp_get_attachment_image filtering is going to work. There's no filter that can override the <img tag returned by that function. As far as I can tell, you can only filter the attributes of the tag. What we need is a <video ...><source="MP4_URL"></video> tag. Thoughts about how we should proceed?

**Comment by mpatek** [comment]
Hey @goldenapples, @danielbachhuber mentioned that you might be able to help out here. I'm wondering how best to present mp4s in HTML, and how we could get GIF attachments (with an mp4 URL stored in postmeta) to display that mp4 instead of the GIF.

**Comment by goldenapples** [comment]
Yeah, you're not going to be able to catch them on output without some heavy regex processing on `the_content` filter. One they're in post content, they're just an `<img>` tag and it doesn't go through any further filters.

It seems to me it would be easier to attach a filter to `media_send_to_editor` and replace the gif with a shortcode or some kind of marker to replace later. I'm working on a similar problem in the plugin I'm building now. [Here's the filter](https://github.com/fusioneng/image-shortcake/commit/13c8a1773eaed04a23437dc2e201b37d56add508) that catches all img tags sent to the editor and replaces them with the shortcode I needed to add. Does that address your question, or were you asking more specifically about the front-end markup to conditionally display mp4 or gif based on feature detection?

**Comment by mpatek** [comment]
@goldenapples great idea, thanks very much! I think the shortcode approach should give us the freedom we need. I suppose we should ensure that this filter comes before the one that you are defining?

**Comment by goldenapples** [comment]
> I suppose we should ensure that this filter comes before the one that you are defining?

Yeah, something like that. Might actually want to set your filter to run at a much later priority and just work off of the attributes array rather than trusting or trying to parse the html passed in. 

My work is still pretty rough, I haven't given enough thought yet to playing nice with other plugins that use the same filter. I guess that's gonna need some though before releasing it.

**Comment by mpatek** [comment]
Sounds good. I'll use a higher (100?) priority since I don't need to use the HTML at all.

**Comment by goldenapples** [comment]
Works for me. You should be safe at that level.

**Comment by danielbachhuber** [comment]
I'd like to keep our use of shortcodes for Image Shortcake. We shouldn't transform inserted GIFs to shortcodes in this plugin.

**Comment by mpatek** [comment]
@danielbachhuber can this plugin use Image Shortcake?

**Comment by danielbachhuber** [comment]
> can this plugin use Image Shortcake?

I was thinking "integrate nicely with, but not be dependent on"

**Comment by mpatek** [comment]
OK. So maybe we just use `media_send_to_editor`, and return a `<video>` tag, rather than a shortcode?

**Comment by goldenapples** [comment]
Does a `<video>` tag meet the output requirements? I'm not sure about fallbacks, haven't investigated it.  

Seems like what you need is something that can can render fairly complex markup into the post content, the syntax of which may change over time as browser technologies modernize. A shortcode would be ideal for that. Alternatively, just output a dummy element which gets processed by some javascript and replaced with the video or embed?

**Comment by danielbachhuber** [comment]
For this plugin, let's keep the behavior of `media_send_to_editor` — send an `<img>` tag to `post_content`. 

On `post_content` filter, we can `preg_match()` on images, see if they're a GIF, and return the proper markup when they are. 

Obviously this is a bit of a hack and shortcodes are much better, but we can do this better implementation in Image Shortcake.

**Comment by mpatek** [comment]
@danielbachhuber so we'll need a way to map GIF URLs to attachment IDs right? Do we already have a way of doing that? I've googled around and found some possible solutions.

**Comment by danielbachhuber** [comment]
> so we'll need a way to map GIF URLs to attachment IDs right? Do we already have a way of doing that?

WordPress adds a `wp-image-<id>` class:

![image](https://cloud.githubusercontent.com/assets/36432/7359196/96e77354-ecf0-11e4-985d-32e1234e5a8d.png)

I think this will be the most reliable way.

**Comment by danielbachhuber** [comment]
@mpatek @noppanit @goldenapples What should the image behavior be for desktop vs. mobile vs. feed?

**Comment by goldenapples** [comment]
Hmm. For one, I'd say lose the `controls` attribute. I think the basic element should look more like a standard animated gif than a video.

Adding `autoplay` is probably good - it looks like mobile browsers won't autoplay anyways so concerns about overloading people's mobile data might not be a problem. It might be a nice future enhancement to have some discoverable controls, like having autoplay begin when the element is fully scrolled into view or having touch/click interaction to start/restart the video. 

There's probably some investigation to be done about fallbacks. (The current mp4-only implementation won't play on Firefox, Opera, Chromium or other OSS-only browsers.)  Would including the original .gif as an `<img>` inside the `<video>` tag work as a fallback for mobile and browsers that can't play mp4's? Or would a flash embed be necessary? Or both?

**Comment by mpatek** [comment]
@danielbachhuber OK to close?

**Comment by danielbachhuber** [comment]
Can we make sure this is documented as a part of our implementation instructions?

**Comment by danielbachhuber** [comment]
This is good enough for now.
